//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.Text.Json.Serialization;
using System.ComponentModel;
using System.Text.Json.Serialization;






namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_0009_000014
{

    public struct Declarations
    {
        public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000014";
    }




    [XmlType(TypeName = "ForeignEntityBasicData", Namespace = Declarations.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public partial class ForeignEntityBasicData
    {

        
		
        [XmlElement(ElementName = "ForeignEntityName", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string ForeignEntityName { get; set; }

        
		
        [XmlElement(ElementName = "CountryISO3166TwoLetterCode", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string CountryISO3166TwoLetterCode { get; set; }

        
		
        [XmlElement(ElementName = "CountryNameCyrillic", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string CountryNameCyrillic { get; set; }

        
		
        [XmlElement(ElementName = "ForeignEntityRegister", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string ForeignEntityRegister { get; set; }

        
		
        [XmlElement(ElementName = "ForeignEntityIdentifier", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string ForeignEntityIdentifier { get; set; }

        
		
        [XmlElement(ElementName = "ForeignEntityOtherData", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string ForeignEntityOtherData { get; set; }

        public ForeignEntityBasicData()
        {
        }
    }
}
