//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;





using System.Text.Json.Serialization;

namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_0009_000009
{

    public struct Declarations
    {
        public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000009";
    }




    [XmlType(TypeName = "ForeignCitizenPlaceOfBirth", Namespace = Declarations.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public partial class ForeignCitizenPlaceOfBirth
    {

        
		
        [XmlElement(ElementName = "CountryCode", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string CountryCode { get; set; }

        
		
        [XmlElement(ElementName = "CountryName", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string CountryName { get; set; }

        
		
        [XmlElement(ElementName = "SettlementName", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string SettlementName { get; set; }

        public ForeignCitizenPlaceOfBirth()
        {
        }
    }
}
