//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;





using System.Text.Json.Serialization;

namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_0009_000007
{

    public struct Declarations
    {
        public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000007";
    }




    [XmlType(TypeName = "ForeignCitizenNames", Namespace = Declarations.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public partial class ForeignCitizenNames
    {

        
		
        [XmlElement(ElementName = "FirstCyrillic", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string FirstCyrillic { get; set; }

        
		
        [XmlElement(ElementName = "LastCyrillic", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string LastCyrillic { get; set; }

        
		
        [XmlElement(ElementName = "OtherCyrillic", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string OtherCyrillic { get; set; }

        
		
        [XmlElement(ElementName = "PseudonimCyrillic", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string PseudonimCyrillic { get; set; }

        
		
        [XmlElement(ElementName = "FirstLatin", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string FirstLatin { get; set; }

        
		
        [XmlElement(ElementName = "LastLatin", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string LastLatin { get; set; }

        
		
        [XmlElement(ElementName = "OtherLatin", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string OtherLatin { get; set; }

        
		
        [XmlElement(ElementName = "PseudonimLatin", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string PseudonimLatin { get; set; }

        public ForeignCitizenNames()
        {
        }
    }
}
