//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;





using System.Text.Json.Serialization;

namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_0009_000006
{

    public struct Declarations
    {
        public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000006";
    }




    [XmlType(TypeName = "PersonIdentifier", Namespace = Declarations.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public partial class PersonIdentifier
    {

        
		
        [XmlElement(ElementName = "EGN", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string EGN { get; set; }

        
		
        [XmlElement(ElementName = "LNCh", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string LNCh { get; set; }

        public PersonIdentifier()
        {
        }
    }
}
