//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;






namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_0009_000011
{

    public struct Declarations
    {
        public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000011";
    }




    [XmlType(TypeName = "ForeignCitizenBasicData", Namespace = Declarations.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public partial class ForeignCitizenBasicData
    {

        
		
        [XmlElement(Type = typeof(R_0009_000007.ForeignCitizenNames), ElementName = "Names", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public R_0009_000007.ForeignCitizenNames Names { get; set; }

        
		
        [XmlElement(ElementName = "BirthDate", Form = XmlSchemaForm.Qualified, DataType = "date", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public DateTime? BirthDate { get; set; }

        
		
        [XmlElement(Type = typeof(R_0009_000009.ForeignCitizenPlaceOfBirth), ElementName = "PlaceOfBirth", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public R_0009_000009.ForeignCitizenPlaceOfBirth PlaceOfBirth { get; set; }

        
		
        [XmlElement(Type = typeof(R_0009_000010.ForeignCitizenIdentityDocument), ElementName = "IdentityDocument", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public R_0009_000010.ForeignCitizenIdentityDocument IdentityDocument { get; set; }

        public ForeignCitizenBasicData()
        {
        }
    }
}
