//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;







namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_10018
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10018";
	}




	[XmlType(TypeName="PaymentReference",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class PaymentReference
	{

		
		
		[XmlElement(ElementName="PaymentReferenceType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentReferenceType { get; set; }

		
		
		[XmlElement(ElementName="PaymentReferenceNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentReferenceNumber { get; set; }

		
		
		[XmlElement(ElementName="PaymentReferenceDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? PaymentReferenceDate { get; set; }

		public PaymentReference()
		{
		}
	}
}
