//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;






namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_10046
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10046";
	}




	[XmlRoot(ElementName="PaymentRequest",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="PaymentRequest",Namespace=Declarations.SchemaVersion)]
	public partial class PaymentRequest
	{

		
		
		[XmlElement(Type=typeof(R_0009_000003.DocumentTypeURI),ElementName="DocumentTypeURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000003.DocumentTypeURI DocumentTypeURI { get; set; }

		
		
		[XmlElement(ElementName="DocumentTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string DocumentTypeName { get; set; }

		
		
		[XmlElement(ElementName="PaymentCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentCode { get; set; }

		
		
		[XmlElement(ElementName="Currency",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string Currency { get; set; }

		
		
		[XmlElement(ElementName="PaymentAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double PaymentAmount { get; set; }

		
		
		[XmlElement(Type=typeof(R_0009_000002.ElectronicServiceProviderBasicData),ElementName="ElectronicServiceProviderBasicData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000002.ElectronicServiceProviderBasicData ElectronicServiceProviderBasicData { get; set; }

		
		
		[XmlElement(Type=typeof(R_10010.ElectronicServiceProviderBankAccount),ElementName="ElectronicServiceProviderBankAccount",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10010.ElectronicServiceProviderBankAccount ElectronicServiceProviderBankAccount { get; set; }

		
		
		[XmlElement(Type=typeof(R_0009_000015.ElectronicServiceRecipient),ElementName="ElectronicServiceRecipient",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000015.ElectronicServiceRecipient ElectronicServiceRecipient { get; set; }

		
		
		[XmlElement(ElementName="PaymentReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentReason { get; set; }

		
		
		[XmlElement(Type=typeof(R_10018.PaymentReference),ElementName="PaymentReference",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10018.PaymentReference PaymentReference { get; set; }

		
		
		[XmlElement(Type=typeof(R_10024.PaymentPeriod),ElementName="PaymentPeriod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10024.PaymentPeriod PaymentPeriod { get; set; }

		
		
		[XmlElement(ElementName="PaymentRequestExpirationDate",Form=XmlSchemaForm.Qualified,DataType="dateTime",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? PaymentRequestExpirationDate { get; set; }

		
		
		[XmlElement(ElementName="AdditionalInformationInPaymentRequest",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string AdditionalInformationInPaymentRequest { get; set; }

		
		
		[XmlElement(ElementName="SUNAUServiceURI",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string SUNAUServiceURI { get; set; }

		
		
		[XmlElement(ElementName="ElectronicAdministrativeServiceSupplierUriRA",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string ElectronicAdministrativeServiceSupplierUriRA { get; set; }

		
		
		[XmlElement(ElementName="ElectronicAdministrativeServiceNotificationURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string ElectronicAdministrativeServiceNotificationURL { get; set; }

		public PaymentRequest()
		{
		}
	}
}
