//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization;






namespace AISTN.ExternalAppAPI.ExternalAppAPI.ePayment.R_10034
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10034";
	}




	[XmlRoot(ElementName="CreditTransferOrder",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="CreditTransferOrder",Namespace=Declarations.SchemaVersion)]
	public partial class CreditTransferOrder
	{

		
		
		[XmlElement(ElementName="PaymentCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentCode { get; set; }

		
		
		[XmlElement(ElementName="CreditTransferAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double CreditTransferAmount { get; set; }

		
		
		[XmlElement(ElementName="PaymentReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string PaymentReason { get; set; }

		
		
		[XmlElement(Type=typeof(R_10018.PaymentReference),ElementName="PaymentReference",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10018.PaymentReference PaymentReference { get; set; }

		
		
		[XmlElement(Type=typeof(R_10024.PaymentPeriod),ElementName="PaymentPeriod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10024.PaymentPeriod PaymentPeriod { get; set; }

		public CreditTransferOrder()
		{
		}
	}
}
