//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:DefaultNamespace", ConfigurationName="ispn")]
public interface ispn
{
    
    [System.ServiceModel.OperationContractAttribute(Action="PLUS", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<PLUSResponse> PLUSAsync(PLUSRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="LOGIN", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<LOGINResponse> LOGINAsync(LOGINRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="QUERY", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<QUERYResponse> QUERYAsync(QUERYRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class RESPONSE
{
    
    private System.Nullable<int> tYPEField;
    
    private ERRORCLASS eRRORField;
    
    private SESSION sESSIONField;
    
    private RESULTSET rESULTSETField;
    
    private double nUMBERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public System.Nullable<int> TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public ERRORCLASS ERROR
    {
        get
        {
            return this.eRRORField;
        }
        set
        {
            this.eRRORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public SESSION SESSION
    {
        get
        {
            return this.sESSIONField;
        }
        set
        {
            this.sESSIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public RESULTSET RESULTSET
    {
        get
        {
            return this.rESULTSETField;
        }
        set
        {
            this.rESULTSETField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public double NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class ERRORCLASS
{
    
    private int idField;
    
    private string dESCRIPTIONField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string DESCRIPTION
    {
        get
        {
            return this.dESCRIPTIONField;
        }
        set
        {
            this.dESCRIPTIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class ISPNCASE
{
    
    private int nUMBERField;
    
    private int yEARField;
    
    private System.Nullable<System.DateTime> dATEField;
    
    private string cOURTField;
    
    private string cOURTNAMEField;
    
    private System.Nullable<System.DateTime> lASTUPDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int YEAR
    {
        get
        {
            return this.yEARField;
        }
        set
        {
            this.yEARField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public System.Nullable<System.DateTime> DATE
    {
        get
        {
            return this.dATEField;
        }
        set
        {
            this.dATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string COURT
    {
        get
        {
            return this.cOURTField;
        }
        set
        {
            this.cOURTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string COURTNAME
    {
        get
        {
            return this.cOURTNAMEField;
        }
        set
        {
            this.cOURTNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
    public System.Nullable<System.DateTime> LASTUPDATE
    {
        get
        {
            return this.lASTUPDATEField;
        }
        set
        {
            this.lASTUPDATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class ISPNSIDE
{
    
    private string nAMEField;
    
    private bool iSPERSONField;
    
    private string sTATENUMBERField;
    
    private int iNVOLVEMENTField;
    
    private string iNVOLVEMENTTEXTField;
    
    private System.Nullable<System.DateTime> lASTUPDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string NAME
    {
        get
        {
            return this.nAMEField;
        }
        set
        {
            this.nAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public bool ISPERSON
    {
        get
        {
            return this.iSPERSONField;
        }
        set
        {
            this.iSPERSONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string STATENUMBER
    {
        get
        {
            return this.sTATENUMBERField;
        }
        set
        {
            this.sTATENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public int INVOLVEMENT
    {
        get
        {
            return this.iNVOLVEMENTField;
        }
        set
        {
            this.iNVOLVEMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string INVOLVEMENTTEXT
    {
        get
        {
            return this.iNVOLVEMENTTEXTField;
        }
        set
        {
            this.iNVOLVEMENTTEXTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
    public System.Nullable<System.DateTime> LASTUPDATE
    {
        get
        {
            return this.lASTUPDATEField;
        }
        set
        {
            this.lASTUPDATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class RESULT
{
    
    private ISPNSIDE sIDEField;
    
    private ISPNCASE cASEField;
    
    private System.Nullable<System.DateTime> lASTUPDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public ISPNSIDE SIDE
    {
        get
        {
            return this.sIDEField;
        }
        set
        {
            this.sIDEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public ISPNCASE CASE
    {
        get
        {
            return this.cASEField;
        }
        set
        {
            this.cASEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public System.Nullable<System.DateTime> LASTUPDATE
    {
        get
        {
            return this.lASTUPDATEField;
        }
        set
        {
            this.lASTUPDATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class RESULTSET
{
    
    private int cOUNTField;
    
    private int rESULTSCOUNTField;
    
    private RESULT[] rESULTSField;
    
    private string lASTIDField;
    
    private System.Nullable<System.DateTime> lASTUPDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int COUNT
    {
        get
        {
            return this.cOUNTField;
        }
        set
        {
            this.cOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int RESULTSCOUNT
    {
        get
        {
            return this.rESULTSCOUNTField;
        }
        set
        {
            this.rESULTSCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RESULTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public RESULT[] RESULTS
    {
        get
        {
            return this.rESULTSField;
        }
        set
        {
            this.rESULTSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string LASTID
    {
        get
        {
            return this.lASTIDField;
        }
        set
        {
            this.lASTIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
    public System.Nullable<System.DateTime> LASTUPDATE
    {
        get
        {
            return this.lASTUPDATEField;
        }
        set
        {
            this.lASTUPDATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
public partial class SESSION
{
    
    private string idField;
    
    private string uSERNAMEField;
    
    private int tTLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string USERNAME
    {
        get
        {
            return this.uSERNAMEField;
        }
        set
        {
            this.uSERNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int TTL
    {
        get
        {
            return this.tTLField;
        }
        set
        {
            this.tTLField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="PLUS", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class PLUSRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string SESSIONID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public double X;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public double Y;
    
    public PLUSRequest()
    {
    }
    
    public PLUSRequest(string SESSIONID, double X, double Y)
    {
        this.SESSIONID = SESSIONID;
        this.X = X;
        this.Y = Y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="PLUSResponse", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class PLUSResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public RESPONSE PLUSReturn;
    
    public PLUSResponse()
    {
    }
    
    public PLUSResponse(RESPONSE PLUSReturn)
    {
        this.PLUSReturn = PLUSReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="LOGIN", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class LOGINRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string USER;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string PASS;
    
    public LOGINRequest()
    {
    }
    
    public LOGINRequest(string USER, string PASS)
    {
        this.USER = USER;
        this.PASS = PASS;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="LOGINResponse", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class LOGINResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public RESPONSE LOGINReturn;
    
    public LOGINResponse()
    {
    }
    
    public LOGINResponse(RESPONSE LOGINReturn)
    {
        this.LOGINReturn = LOGINReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="QUERY", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class QUERYRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:DefaultNamespace", Order=0)]
    public string SESSIONID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:DefaultNamespace", Order=1)]
    public string STATENUMBER;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:DefaultNamespace", Order=2)]
    public int INVOLVEMENT;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:DefaultNamespace", Order=3)]
    public string STARTID;
    
    public QUERYRequest()
    {
    }
    
    public QUERYRequest(string SESSIONID, string STATENUMBER, int INVOLVEMENT, string STARTID)
    {
        this.SESSIONID = SESSIONID;
        this.STATENUMBER = STATENUMBER;
        this.INVOLVEMENT = INVOLVEMENT;
        this.STARTID = STARTID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="QUERYResponse", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
public partial class QUERYResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public RESPONSE QUERYReturn;
    
    public QUERYResponse()
    {
    }
    
    public QUERYResponse(RESPONSE QUERYReturn)
    {
        this.QUERYReturn = QUERYReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface ispnChannel : ispn, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class ispnClient : System.ServiceModel.ClientBase<ispn>, ispn
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public ispnClient() : 
            base(ispnClient.GetDefaultBinding(), ispnClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.Domino.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ispnClient(EndpointConfiguration endpointConfiguration) : 
            base(ispnClient.GetBindingForEndpoint(endpointConfiguration), ispnClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ispnClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(ispnClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ispnClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(ispnClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ispnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<PLUSResponse> PLUSAsync(PLUSRequest request)
    {
        return base.Channel.PLUSAsync(request);
    }
    
    public System.Threading.Tasks.Task<LOGINResponse> LOGINAsync(LOGINRequest request)
    {
        return base.Channel.LOGINAsync(request);
    }
    
    public System.Threading.Tasks.Task<QUERYResponse> QUERYAsync(QUERYRequest request)
    {
        return base.Channel.QUERYAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.Domino))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.Domino))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost/");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return ispnClient.GetBindingForEndpoint(EndpointConfiguration.Domino);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return ispnClient.GetEndpointAddress(EndpointConfiguration.Domino);
    }
    
    public enum EndpointConfiguration
    {
        
        Domino,
    }
}
